name: Build and deploy Laravel app to Azure Web App - rakk-gears

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          extensions: mbstring, bcmath, intl, pdo_mysql

      - name: Install Composer dependencies
        run: |
          composer install --prefer-dist --no-progress --no-interaction --optimize-autoloader --no-dev

      - name: Prepare deployment package
        run: |
          mkdir deploy
          cp -r app bootstrap config database public resources routes artisan composer.json composer.lock deploy/
          cp -r vendor deploy/
          # Storage can be tricky, better to keep it persistent in Azure
          mkdir -p deploy/storage/framework/{sessions,views,cache}
          mkdir -p deploy/storage/logs
          chmod -R 775 deploy/storage

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: php-app
          path: deploy

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: php-app

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_6B683814F89E466CAAAC34CA0A83621D }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_47BDC39AD1F840C586FF8F675382FF66 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_61FAB2A20A73479B8CA3E0E34498E770 }}

      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: 'rakk-gears'
          slot-name: 'Production'
          package: ./php-app
